// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadDotenv } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js projects usually keep local secrets in .env.local.
// Load it first, then fall back to default .env resolution.
loadDotenv({ path: ".env.local" });
loadDotenv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
